var questions = [
  "My biggest concern for the future is…",
  "If I were an animal, I would be a…",
  "Saying “um” is one of the worst things you can do in public speaking.",
  "Advice for Little Red Riding Hood",
  "Cities are for people, not cars.",
  "Children should watch less/no television.",
  "Why are manners important?",
  "Uniforms smother individuality.",
  "Why is a sense of humor important?",
  '“Normal” is decided by society.',
  "Real learning happens outside the classroom.",
  "Wisdom vs. intelligence",
  "Talking to someone vs. talking with someone",
  "Advertisements targeted to children immoral.",
  "Pets are for people without children",
  "What human quality do we need more of?",
  "When is lying a good idea?",
  "If I ruled the world…",
  "The effects of color on people",
  "Poor health begins in the mind.",
  "Beauty is in the eye of the beholder.",
  "Poverty is a state of mind.",
  "Is it really that great being young?",
  "One thing that I would impress someone with is…",
  "High salaries of athletes, actors, etc.",
  "My most vivid memory from the past year",
  "My favorite of the five senses",
  "If I were the opposite sex/president/an author/rich, I would…",
  "If I had a mission statement",
  "People often stereotype…",
  "Why do teenagers smoke?",
  "You’re the prey (ant, gazelle, etc.) – convince the predator (anteater, lion, etc.) to not eat you.",
  "A favorite nickname of yours",
  "Three uses for a product other than its intended use (pencil, cup, scissors, etc.)",
  "If you were a salesperson, sell the audience a piece of your clothing.",
  "The most difficult thing I’ve ever done",
  "My best job ever",
  "Explain the rules to your favorite game.",
  "Which came first: the chicken or the egg?",
  "How to make a pizza",
  "How to make your favorite meal",
  "How to be a beekeeper",
  "Ghosts you’d like to meet",
  "The morality of zoos",
  "Dogs are better than cats (or vice versa)",
  "Discuss your favorite movie, book, etc.",
  "Your first memory",
  "Real vs. fake Christmas trees",
  "Bottles vs. cans",
  "Should smoking be allowed in public spaces?",
  "Review the last movie you saw.",
  "Your favorite hybrid animals",
  "Speed dating",
  "The most successful person you know",
  "How to buy a car",
  "Your favorite smart phone app",
  "How to become a comedian",
  "Violence on TV",
  "Uniforms in school",
  "Three things you do well",
];
